import hljs from 'highlight.js/lib/core'

import 'highlight.js/lib/languages/bash'
import 'highlight.js/lib/languages/c'
import 'highlight.js/lib/languages/cmake'
import 'highlight.js/lib/languages/cpp'
import 'highlight.js/lib/languages/csharp'
import 'highlight.js/lib/languages/css'
import 'highlight.js/lib/languages/diff'
import 'highlight.js/lib/languages/dockerfile'
import 'highlight.js/lib/languages/go'
import 'highlight.js/lib/languages/groovy'
import 'highlight.js/lib/languages/ini'
import 'highlight.js/lib/languages/java'
import 'highlight.js/lib/languages/javascript'
import 'highlight.js/lib/languages/json'
import 'highlight.js/lib/languages/kotlin'
import 'highlight.js/lib/languages/lua'
import 'highlight.js/lib/languages/makefile'
import 'highlight.js/lib/languages/markdown'
import 'highlight.js/lib/languages/perl'
import 'highlight.js/lib/languages/php'
import 'highlight.js/lib/languages/plaintext'
import 'highlight.js/lib/languages/powershell'
import 'highlight.js/lib/languages/properties'
import 'highlight.js/lib/languages/python'
import 'highlight.js/lib/languages/r'
import 'highlight.js/lib/languages/ruby'
import 'highlight.js/lib/languages/rust'
import 'highlight.js/lib/languages/scala'
import 'highlight.js/lib/languages/shell'
import 'highlight.js/lib/languages/sql'
import 'highlight.js/lib/languages/swift'
import 'highlight.js/lib/languages/typescript'
import 'highlight.js/lib/languages/xml'
import 'highlight.js/lib/languages/yaml'

export default hljs
